/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class DeleteBebidas extends javax.swing.JInternalFrame {
    private int idSelecionado = -1;
    /**
     * Creates new form ViewBebidas
     */
    public DeleteBebidas() {
        
        initComponents();        
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBebidas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("ML Bebidas - Deletar Bebidas");

        tabelaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabelaBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBebidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBebidas);

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mlbebidas.BancoDeDados bd = new mlbebidas.BancoDeDados();
        bd.conectar();
        if(idSelecionado != -1){
            bd.excluirBebidas(idSelecionado);
        }
        bd.desconectar();
        carregarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBebidasMouseClicked
        if(evt.getClickCount() == 1){
            int linhaSelecionada = tabelaBebidas.getSelectedRow();
            
            if(linhaSelecionada != -1){
                idSelecionado = Integer.parseInt(tabelaBebidas.getValueAt(linhaSelecionada, 0).toString());                
            }
        }
    }//GEN-LAST:event_tabelaBebidasMouseClicked
    public void carregarTabela() {
        mlbebidas.BancoDeDados bd = new mlbebidas.BancoDeDados();
        bd.conectar();
        try {
            ResultSet rs = bd.listarBebidas();
            DefaultTableModel modelo = new DefaultTableModel();
            
            ResultSetMetaData metaData = rs.getMetaData();
            int colunas = metaData.getColumnCount();
            
            for (int i = 1; i <= colunas; i++) {
                modelo.addColumn(metaData.getColumnName(i));
            }
            
            while(rs.next()){
                Object[] linha = new Object[colunas];
                for (int i = 0; i < colunas; i++) {
                    linha[i] = rs.getObject(i + 1);
                }
                modelo.addRow(linha);
            }
            tabelaBebidas.setModel(modelo);
        } catch (SQLException e) {
            System.out.println("Erro ao carregar a tabela: " + e.getMessage());
        } finally {
            bd.desconectar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBebidas;
    // End of variables declaration//GEN-END:variables
}
