/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class UpdateBebidas extends javax.swing.JInternalFrame {

    private int idSelecionado = -1;

    /**
     * Creates new form ViewBebidas
     */
    public UpdateBebidas() {

        initComponents();
        txt_nome.setEditable(false);
        txt_quantidade.setEditable(false);
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBebidas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_quantidade = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ML Bebidas - Atualizar Bebidas");

        tabelaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabelaBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBebidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaBebidas);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_nome.setText("Nome");

        lbl_quantidade.setText("Quantidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_quantidade)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 24, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(lbl_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_quantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mlbebidas.BancoDeDados bd = new mlbebidas.BancoDeDados();
        bd.conectar();
    if (idSelecionado != -1) {
        String novoNome = txt_nome.getText().trim();
        try {
            int novaQuantidade = Integer.parseInt(txt_quantidade.getText());
            if (!novoNome.isEmpty() && novaQuantidade >= 0) {
                bd.atualizarBebidas(idSelecionado, novoNome, novaQuantidade);
            }
        } catch (NumberFormatException e) {
            System.out.println("Quantidade inválida. Digite um número inteiro.");
            
        }
    }
        bd.desconectar();
        carregarTabela();
        txt_nome.setText("");
        txt_quantidade.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBebidasMouseClicked
        if (evt.getClickCount() == 1) {
            int linhaSelecionada = tabelaBebidas.getSelectedRow();

            if (linhaSelecionada != -1) {
                idSelecionado = Integer.parseInt(tabelaBebidas.getValueAt(linhaSelecionada, 0).toString());
                String nome = tabelaBebidas.getValueAt(linhaSelecionada, 1).toString();
                String quantidade = tabelaBebidas.getValueAt(linhaSelecionada, 2).toString();

                txt_nome.setText(nome);
                txt_quantidade.setText(quantidade);
                txt_nome.setEditable(true);
                txt_quantidade.setEditable(true);
            }
        }
    }//GEN-LAST:event_tabelaBebidasMouseClicked
    public void carregarTabela() {
        mlbebidas.BancoDeDados bd = new mlbebidas.BancoDeDados();
        bd.conectar();
        try {
            ResultSet rs = bd.listarBebidas();
            DefaultTableModel modelo = new DefaultTableModel();

            ResultSetMetaData metaData = rs.getMetaData();
            int colunas = metaData.getColumnCount();

            for (int i = 1; i <= colunas; i++) {
                modelo.addColumn(metaData.getColumnName(i));
            }

            while (rs.next()) {
                Object[] linha = new Object[colunas];
                for (int i = 0; i < colunas; i++) {
                    linha[i] = rs.getObject(i + 1);
                }
                modelo.addRow(linha);
            }
            tabelaBebidas.setModel(modelo);
        } catch (SQLException e) {
            System.out.println("Erro ao carregar a tabela: " + e.getMessage());
        } finally {
            bd.desconectar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JTable tabelaBebidas;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
