/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class ViewBebidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewBebidas
     */
    public ViewBebidas() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBebidas = new javax.swing.JTable();

        setClosable(true);
        setTitle("ML Bebidas - Visualizar Bebidas");

        jTableBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTableBebidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void carregarTabela() {
        mlbebidas.BancoDeDados bd = new mlbebidas.BancoDeDados();
        bd.conectar();
        try {
            ResultSet rs = bd.listarBebidas();
            DefaultTableModel modelo = new DefaultTableModel();
            
            ResultSetMetaData metaData = rs.getMetaData();
            int colunas = metaData.getColumnCount();
            
            for (int i = 1; i <= colunas; i++) {
                modelo.addColumn(metaData.getColumnName(i));
            }
            
            while(rs.next()){
                Object[] linha = new Object[colunas];
                for (int i = 0; i < colunas; i++) {
                    linha[i] = rs.getObject(i + 1);
                }
                modelo.addRow(linha);
            }
            jTableBebidas.setModel(modelo);
        } catch (SQLException e) {
            System.out.println("Erro ao carregar a tabela: " + e.getMessage());
        } finally {
            bd.desconectar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBebidas;
    // End of variables declaration//GEN-END:variables
}
